version: '3.8'

services:
  app:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image:
      ustaf/tetring-server:1.4
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart:
      on-failure
    depends_on:
      - redis
      - mysql
    env_file:
      - ./.env
    networks:
      - tetring-network

  redis:
    image: redis:latest
#    platform: linux/amd64
    command:
      redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - tetring-network

  mysql:
    image: mysql:8.0.37
#    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 3s
#      timeout: 20s
#      retries: 5
    networks:
      - tetring-network

networks:
  tetring-network:
    driver: bridge