name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_SECRET_KEY: ${{ secrets.GOOGLE_SECRET_KEY }}
      NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
      NAVER_SECRET_KEY: ${{ secrets.NAVER_SECRET_KEY }}
      KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
      KAKAO_SECRET_KEY: ${{ secrets.KAKAO_SECRET_KEY }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

#    steps:
#    - name: 코드 체크아웃
#      uses: actions/checkout@v3
#
#    - name: Docker Hub 로그인
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#
#    - name: 도커 이미지 빌드 및 푸시
#      uses: docker/build-push-action@v4
#      with:
#        context: .
#        push: true
#        tags: your-dockerhub-username/your-image-name:latest
#
#    - name: 서버에 배포
#      uses: appleboy/ssh-action@v0.1.8
#      with:
#        host: ${{ secrets.SERVER_HOST }}
#        username: ${{ secrets.SERVER_USER }}
#        key: ${{ secrets.SERVER_SSH_KEY }}
#        script: |
#          cd /path/to/your/project
#          docker-compose pull
#          docker-compose up -d